name: Auto Format

on:
  push:
    branches: [develop, feature/*]
  workflow_dispatch:

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix config files format
        run: |
          # Fix Prettier config if it uses ES modules
          if [ -f .prettierrc.js ] && grep -q "export default" .prettierrc.js; then
            echo "Converting .prettierrc.js to .prettierrc.json for compatibility..."
            echo '{
              "semi": true,
              "singleQuote": true,
              "tabWidth": 2,
              "useTabs": false
            }' > .prettierrc.json
            rm .prettierrc.js
            echo "Prettier config converted to JSON format"
          fi

      - name: Run ESLint with auto-fix
        run: npx eslint . --fix --format=stylish
        continue-on-error: true

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: auto-format code and fix configuration compatibility'
          title: '🤖 Auto-format code and fix configuration'
          body: |
            ## Auto-formatting and Configuration Updates

            This PR contains automatic changes made by:
            - ESLint auto-fix (using stylish formatter for compatibility)
            - Prettier formatting  
            - Configuration file format fixes for ESLint 7.x compatibility

            ### Files changed:
            - Code files reformatted for consistency
            - Configuration files converted to compatible formats

            ### Configuration fixes:
            - Converted `.prettierrc.js` to `.prettierrc.json` for compatibility

            ### What to do:
            - ✅ Review the changes
            - ✅ Merge if formatting and fixes look correct
            - ❌ Close if changes are not desired

            ---
            *This PR was created automatically by the Auto Format workflow.*
          branch: auto-format-${{ github.run_number }}-${{ github.run_attempt }}
          delete-branch: true
          assignees: ${{ github.actor }}
          labels: |
            automated
            formatting
            configuration
            code-style
